apiVersion: v1
kind: Service
metadata:
  labels:
    app: epsilon-core
  name: epsilon-core-service
  namespace: epsilon
spec:
  selector:
    app: epsilon-core
  ports:
    - protocol: "TCP"
      port: 8082
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: epsilon-core
  name: epsilon-core
  namespace: epsilon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: epsilon-core
  template:
    metadata:
      labels:
        app: epsilon-core
    spec:
      containers:
        - name: epsilon-core
          image: com.angushenderson/epsilon-core:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_SERVICE
              value: kafka-service:9092